"use strict";

const SENSITIVE_RULES = [
  // ═══════════════════════════════════════════════════════════════
  //  Tokens & Keys
  // ═══════════════════════════════════════════════════════════════
  { id: "aws-access-key", cat: "Tokens & Keys", desc: "AWS Access Key ID", regex: "A(BIA|CCA|GPA|I(DA|PA)|KIA|N(PA|VA)|PKA|ROA|S(CA|IA))[a-zA-Z0-9]{16,17}(?![a-zA-Z0-9+/=])", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "aws-secret-key", cat: "Tokens & Keys", desc: "AWS Secret Access Key", regex: "(?i)aws([^;]{0,32}?)['\"][0-9a-zA-Z/+=]{40}['\"]", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "amazon-mws-auth", cat: "Tokens & Keys", desc: "Amazon MWS Auth Token", regex: "(?i)amzn\\.mws\\.[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "google-api-key", cat: "Tokens & Keys", desc: "Google API Key", regex: "AIza[0-9A-Za-z\\-_]{35}", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "google-oauth-token", cat: "Tokens & Keys", desc: "Google OAuth Access Token", regex: "ya29\\.[0-9A-Za-z\\-_]{32,48}", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "google-oauth-client-id", cat: "Tokens & Keys", desc: "Google OAuth Client ID", regex: "\\.apps\\.googleusercontent\\.com", refiner: "\\d{1,20}-\\w{32}$", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "google-oauth-client-secret", cat: "Tokens & Keys", desc: "Google OAuth Client Secret", regex: "GOCSPX-[0-9a-zA-Z\\-_]{28}", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "mailgun-api-key", cat: "Tokens & Keys", desc: "MailGun API Key", regex: "key-[0-9a-f]{32}(?!\\w)", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "nuget-api-key", cat: "Tokens & Keys", desc: "NuGet API Key", regex: "oy2[a-z0-9]{43}(?![a-z0-9])", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "sendgrid-api-key", cat: "Tokens & Keys", desc: "SendGrid API Key", regex: "SG\\.[0-9A-Za-z\\-_]{22}\\.[0-9A-Za-z\\-_]{43}", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "slack-token", cat: "Tokens & Keys", desc: "Slack Token", regex: "x(ox[psboare]|app)(-[a-zA-Z0-9]{1,64}){1,5}", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "square-token", cat: "Tokens & Keys", desc: "Square Token", regex: "sq0(atp|csp|idp)-[0-9A-Za-z\\-_]{22,43}", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "stripe-api-key", cat: "Tokens & Keys", desc: "Stripe API Key", regex: "[sr]k_(live|test)_[0-9a-zA-Z]{24}", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "stripe-webhook-secret", cat: "Tokens & Keys", desc: "Stripe Webhook Secret", regex: "whsec_[0-9a-zA-Z]{32}", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "twilio-account-sid", cat: "Tokens & Keys", desc: "Twilio Account SID", regex: "SK[0-9a-zA-Z]{32}(?![a-zA-Z0-9+/=?_%)])", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "github-token", cat: "Tokens & Keys", desc: "Github Token", regex: "gh[pousr]_[A-Za-z0-9]{36}", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "github-fine-grained-pat", cat: "Tokens & Keys", desc: "Github fine-grained PAT", regex: "github_pat_[0-9a-zA-Z]{22}_[0-9a-zA-Z]{59}", sections: ["resp_body", "resp_headers"], severity: "critical" },
  { id: "openai-api-key", cat: "Tokens & Keys", desc: "OpenAI API Key", regex: "sk-[a-zA-Z0-9]{40,128}(?![\\w\\-])", sections: ["resp_body", "resp_headers"], severity: "critical" },

  // ═══════════════════════════════════════════════════════════════
  //  General Secrets
  // ═══════════════════════════════════════════════════════════════
  { id: "pem-certificate", cat: "General Secrets", desc: "PEM/Certificate", regex: "-----BEGIN", sections: ["resp_body", "resp_headers"], severity: "high" },
  { id: "generic-api-key", cat: "General Secrets", desc: "Generic API Key", regex: "(?i)api.{0,5}key[^&|;?,]{0,32}?['\"][a-zA-Z0-9_\\-+=\\/\\\\]{10,}['\"]", sections: ["resp_body", "resp_headers"], severity: "high" },
  { id: "generic-secret", cat: "General Secrets", desc: "Generic Secret", regex: "(?i)secret[^&|;?,]{0,32}?['\"][a-zA-Z0-9_\\-+=\\/\\\\]{10,}['\"]", sections: ["resp_body", "resp_headers"], severity: "high" },
  { id: "env-file-ref", cat: "General Secrets", desc: ".env file reference", regex: "\\.env", sections: ["resp_body", "resp_headers"], severity: "medium" },
  { id: "private-ipv4", cat: "General Secrets", desc: "Private IPv4", regex: "1(0(\\.[0-2]\\d{0,2}){3}|27(\\.[0-2]\\d{0,2}){3}|92\\.168(\\.[0-2]\\d{0,2}){2}|72\\.(1[6-9]|2\\d|3[0-2])(\\.[0-2]\\d{0,2}){2})(?![\\d.])", sections: ["resp_body", "resp_headers"], severity: "medium" },
  { id: "email", cat: "General Secrets", desc: "Email", regex: "[a-zA-Z0-9]@[a-zA-Z0-9\\-\\.]{3,128}\\.[a-zA-Z0-9]{2,32}(?![\\w\\\\])", sections: ["resp_body", "resp_headers"], severity: "medium" },

  // ═══════════════════════════════════════════════════════════════
  //  Cloud & Webhooks
  // ═══════════════════════════════════════════════════════════════
  { id: "slack-webhook", cat: "Cloud & Webhooks", desc: "Slack Webhook", regex: "hooks\\.slack\\.com/services/T[a-zA-Z0-9_]{8,10}/B[a-zA-Z0-9_]{8,10}/[a-zA-Z0-9_]{24}", sections: ["resp_body", "req_url"], severity: "medium" },
  { id: "ms-teams-webhook-connector", cat: "Cloud & Webhooks", desc: "MS Teams Webhook (connector)", regex: "outlook\\.office(365)?\\.com/webhook/[\\w\\-@]{1,128}", sections: ["resp_body", "req_url"], severity: "medium" },
  { id: "ms-teams-webhook-incoming", cat: "Cloud & Webhooks", desc: "MS Teams Webhook (incoming)", regex: "\\.webhook\\.office\\.com", sections: ["resp_body", "req_url"], severity: "medium" },
  { id: "firebase-url", cat: "Cloud & Webhooks", desc: "Firebase URL", regex: "\\.(firebase(io\\.com|database\\.app))", sections: ["resp_body", "req_url"], severity: "high" },
  { id: "aws-s3-bucket", cat: "Cloud & Webhooks", desc: "AWS S3 Bucket", regex: "s3(\\.dualstack|-acce(lerate|sspoint))?\\.([a-z]{1,8}-[a-z]{1,16}-\\d{1,3}\\.)?amazonaws\\.com", sections: ["resp_body", "req_url"], severity: "high" },
  { id: "azure-blob-storage", cat: "Cloud & Webhooks", desc: "Azure Blob Storage", regex: "blob\\.core\\.windows\\.net", sections: ["resp_body", "req_url"], severity: "high" },
  { id: "gcloud-storage", cat: "Cloud & Webhooks", desc: "Google Cloud Storage", regex: "gs://[a-z\\d\\-]{3,63}", sections: ["resp_body", "req_url"], severity: "high" },
  { id: "amazon-arn", cat: "Cloud & Webhooks", desc: "Amazon ARN", regex: "arn:aws(-(cn|us-gov|iso-[bcd]))?:[\\w/.\\-]{1,63}:([\\w/.\\-]{0,63}:){2}([\\w:/.\\-]{0,1023})", sections: ["resp_body", "req_url"], severity: "high" },

  // ═══════════════════════════════════════════════════════════════
  //  Sensitive Files
  // ═══════════════════════════════════════════════════════════════
  { id: "file-agilekeychain", cat: "Sensitive Files", desc: "1Password Keychain (.agilekeychain)", regex: "\\.agilekeychain(?:[?#]|$)", sections: ["req_url"], severity: "critical" },
  { id: "file-asa", cat: "Sensitive Files", desc: "ASP config (.asa)", regex: "\\.asa(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-keychain", cat: "Sensitive Files", desc: "macOS Keychain (.keychain)", regex: "\\.keychain(?:[?#]|$)", sections: ["req_url"], severity: "critical" },
  { id: "file-cscfg", cat: "Sensitive Files", desc: "Azure config (.cscfg)", regex: "\\.cscfg(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-bak", cat: "Sensitive Files", desc: "Backup file (.bak)", regex: "\\.bak(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-cer", cat: "Sensitive Files", desc: "Certificate (.cer)", regex: "\\.cer(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-crt", cat: "Sensitive Files", desc: "Certificate (.crt)", regex: "\\.crt(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-p7b", cat: "Sensitive Files", desc: "Certificate (.p7b)", regex: "\\.p7b(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-zip", cat: "Sensitive Files", desc: "Archive (.zip)", regex: "\\.zip(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-tar", cat: "Sensitive Files", desc: "Archive (.tar)", regex: "\\.tar(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-gz", cat: "Sensitive Files", desc: "Archive (.gz)", regex: "\\.gz(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-tgz", cat: "Sensitive Files", desc: "Archive (.tgz)", regex: "\\.tgz(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-rar", cat: "Sensitive Files", desc: "Archive (.rar)", regex: "\\.rar(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-config", cat: "Sensitive Files", desc: "Config file (.config)", regex: "\\.config(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-dayone", cat: "Sensitive Files", desc: "Day One journal (.dayone)", regex: "\\.dayone(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-docx", cat: "Sensitive Files", desc: "Document (.docx)", regex: "\\.docx(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-doc", cat: "Sensitive Files", desc: "Document (.doc)", regex: "\\.doc(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-rtf", cat: "Sensitive Files", desc: "Document (.rtf)", regex: "\\.rtf(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-xlsx", cat: "Sensitive Files", desc: "Spreadsheet (.xlsx)", regex: "\\.xlsx(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-xls", cat: "Sensitive Files", desc: "Spreadsheet (.xls)", regex: "\\.xls(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-csv", cat: "Sensitive Files", desc: "Spreadsheet (.csv)", regex: "\\.csv(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-gnucash", cat: "Sensitive Files", desc: "GnuCash (.gnucash)", regex: "\\.gnucash(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-inc", cat: "Sensitive Files", desc: "Include file (.inc)", regex: "\\.inc(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-java", cat: "Sensitive Files", desc: "Java source (.java)", regex: "\\.java(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-jks", cat: "Sensitive Files", desc: "Java KeyStore (.jks)", regex: "\\.jks(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-kwallet", cat: "Sensitive Files", desc: "KDE Wallet (.kwallet)", regex: "\\.kwallet(?:[?#]|$)", sections: ["req_url"], severity: "critical" },
  { id: "file-xpl", cat: "Sensitive Files", desc: "Exploit file (.xpl)", regex: "\\.xpl(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-log", cat: "Sensitive Files", desc: "Log file (.log)", regex: "\\.log(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-tpm", cat: "Sensitive Files", desc: "TPM key (.tpm)", regex: "\\.tpm(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-bek", cat: "Sensitive Files", desc: "BitLocker key (.bek)", regex: "\\.bek(?:[?#]|$)", sections: ["req_url"], severity: "critical" },
  { id: "file-mdf", cat: "Sensitive Files", desc: "Database (.mdf)", regex: "\\.mdf(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-sdf", cat: "Sensitive Files", desc: "Database (.sdf)", regex: "\\.sdf(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-pcap", cat: "Sensitive Files", desc: "Packet capture (.pcap)", regex: "\\.pcap(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-old", cat: "Sensitive Files", desc: "Old backup (.old)", regex: "\\.old(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-ovpn", cat: "Sensitive Files", desc: "OpenVPN config (.ovpn)", regex: "\\.ovpn(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-pdf", cat: "Sensitive Files", desc: "Document (.pdf)", regex: "\\.pdf(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-php", cat: "Sensitive Files", desc: "PHP source (.php)", regex: "\\.php(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-psafe3", cat: "Sensitive Files", desc: "Password Safe (.psafe3)", regex: "\\.psafe3(?:[?#]|$)", sections: ["req_url"], severity: "critical" },
  { id: "file-yml", cat: "Sensitive Files", desc: "YAML config (.yml)", regex: "\\.yml(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-pkcs12", cat: "Sensitive Files", desc: "Certificate (.pkcs12)", regex: "\\.pkcs12(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-p12", cat: "Sensitive Files", desc: "Certificate (.p12)", regex: "\\.p12(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-pfx", cat: "Sensitive Files", desc: "Certificate (.pfx)", regex: "\\.pfx(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-pkr", cat: "Sensitive Files", desc: "PGP public keyring (.pkr)", regex: "\\.pkr(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-skr", cat: "Sensitive Files", desc: "PGP secret keyring (.skr)", regex: "\\.skr(?:[?#]|$)", sections: ["req_url"], severity: "critical" },
  { id: "file-asc", cat: "Sensitive Files", desc: "PGP armored key (.asc)", regex: "\\.asc(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-pem", cat: "Sensitive Files", desc: "PEM key/cert (.pem)", regex: "\\.pem(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-private-key", cat: "Sensitive Files", desc: "Private key (.private_key)", regex: "\\.private_key(?:[?#]|$)", sections: ["req_url"], severity: "critical" },
  { id: "file-pptx", cat: "Sensitive Files", desc: "Presentation (.pptx)", regex: "\\.pptx(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-ppt", cat: "Sensitive Files", desc: "Presentation (.ppt)", regex: "\\.ppt(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-py", cat: "Sensitive Files", desc: "Python source (.py)", regex: "\\.py(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-rdp", cat: "Sensitive Files", desc: "Remote Desktop (.rdp)", regex: "\\.rdp(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-rb", cat: "Sensitive Files", desc: "Ruby source (.rb)", regex: "\\.rb(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-sqlite", cat: "Sensitive Files", desc: "SQLite database (.sqlite)", regex: "\\.sqlite(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-sqlite3", cat: "Sensitive Files", desc: "SQLite database (.sqlite3)", regex: "\\.sqlite3(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-plist", cat: "Sensitive Files", desc: "Property list (.plist)", regex: "\\.plist(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-exports", cat: "Sensitive Files", desc: "NFS exports (.exports)", regex: "\\.exports(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-functions", cat: "Sensitive Files", desc: "Shell functions (.functions)", regex: "\\.functions(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-extra", cat: "Sensitive Files", desc: "Extra config (.extra)", regex: "\\.extra(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-tmp", cat: "Sensitive Files", desc: "Temp file (.tmp)", regex: "\\.tmp(?:[?#]|$)", sections: ["req_url"], severity: "medium" },
  { id: "file-terraform-tfvars", cat: "Sensitive Files", desc: "Terraform variables (terraform.tfvars)", regex: "terraform\\.tfvars(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-txt", cat: "Sensitive Files", desc: "Text file (.txt)", regex: "\\.txt(?:[?#]|$)", sections: ["req_url"], severity: "low" },
  { id: "file-tblk", cat: "Sensitive Files", desc: "Tunnelblick VPN (.tblk)", regex: "\\.tblk(?:[?#]|$)", sections: ["req_url"], severity: "high" },
  { id: "file-fve", cat: "Sensitive Files", desc: "BitLocker metadata (.fve)", regex: "\\.fve(?:[?#]|$)", sections: ["req_url"], severity: "critical" },
  { id: "file-xml", cat: "Sensitive Files", desc: "XML file (.xml)", regex: "\\.xml(?:[?#]|$)", sections: ["req_url"], severity: "low" },
];
